### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by LuigiElleBalotta** [aurasphere/dnd-achievement-tracker#1]
Ciao,
sto progettando un app per d&d che sarà abbastanza grossa, se tutt'ora qualcuno ci gioca potete contattarmi per saperne di più e magari aiutarmi con i commit :)

Scusate l'issue e lo spam nella mail ma non saprei come contattarvi altrimenti!

**Comment by aurasphere** [comment]
Ciao Luigi, puoi scrivermi alla mail che trovi sul repo!
